= Clara Rules
:url-docs: http://www.clara-rules.org
:url-first-steps: http://www.clara-rules.org/docs/firststeps/
:url-repo: https://github.com/mlotysz/clara-rules
:url-upstream: https://github.com/oracle-samples/clara-rules

image:{url-repo}/actions/workflows/clojure.yml/badge.svg[Build Status, link={url-repo}/actions/workflows/clojure.yml]

A forward-chaining rules engine for Clojure(Script).

This is a fork of {url-upstream}[oracle-samples/clara-rules] with a modernized build system (Clojure CLI / deps.edn instead of Leiningen).
See {url-docs}[clara-rules.org] for documentation.

== Usage

Here's a simple example. Complete documentation is at {url-first-steps}[clara-rules.org].

[source,clojure]
----
(ns clara.support-example
  (:require [clara.rules :refer :all]))

(defrecord SupportRequest [client level])

(defrecord ClientRepresentative [name client])

(defrule is-important
  "Find important support requests."
  [SupportRequest (= :high level)]
  =>
  (println "High support requested!"))

(defrule notify-client-rep
  "Find the client representative and send a notification of a support request."
  [SupportRequest (= ?client client)]
  [ClientRepresentative (= ?client client) (= ?name name)] ; Join via the ?client binding.
  =>
  (println "Notify" ?name "that"  ?client "has a new support request!"))

;; Run the rules! We can just use Clojure's threading macro to wire things up.
(-> (mk-session)
    (insert (->ClientRepresentative "Alice" "Acme")
            (->SupportRequest "Acme" :high))
    (fire-rules))

;;;; Prints this:

;; High support requested!
;; Notify Alice that Acme has a new support request!
----

== Building

Requires Java 21+ and Node.js (for ClojureScript tests).

[source,bash]
----
clojure -T:build javac      # Compile Java sources (required before tests)
clojure -M:test              # Run tests
clojure -M:test-generative   # Run generative tests
clojure -M:test-performance  # Run performance tests
clojure -T:build jar         # Build JAR
----

ClojureScript tests compile to a Node.js target:

[source,bash]
----
clojure -M:cljs-test -m cljs-build simple   # Compile CLJS tests
node target/js/test-simple.js               # Run CLJS tests
----

== Community

Questions about Clara Rules can be posted to the https://groups.google.com/forum/?hl=en#!forum/clara-rules[Google Group] or the https://clojurians.slack.com/messages/clara/[#clara Slack channel] on Clojurians.

== License

Copyright (C) 2018, 2025 Oracle and/or its affiliates.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
